_BASE_: "../base_model_bert_l12_h768.yaml"

SHARED_TARGETS:

  - 
    NAME: 'ImageNet1k'
    SHARED_TARGETS_CFG:
      FILE_PATH: 'open_source_dataset/imagenet_class_name_CLIP_with_endoftext.pkl'
      DISTRIBUTED: False



TASKS:

  - 
    NAME: imagenet
    DATASETS:
      TRAIN: 'ImageNetDataset'
      VAL: 'ImageNetDataset'
      TASK_TYPE: 'image_classification'
      DATASET_NAME: 'ImageNet1k'
      TARGET_SET: ['ImageNet1k']
      
    DATALOADER:
      TRAIN_BATCH_SIZE: 64
      TEST_BATCH_SIZE: 512
      NUM_WORKERS: 4 # will be used as numworker for testing loader 
      FEATS_FOLDER: 'open_source_dataset/imagenet'
      S3_PATH: 'cluster2:s3://imagenet'
      ANNO_FOLDER:  'open_source_dataset/imagenet/meta'
      SAMPLING_WEIGHT: 1.0
      CLASS_NAME_FILE: 'open_source_dataset/imagenet_class_name.pkl'
      DATA_PERCENTAGE: 0.01
    MODEL:
      MAX_SEQ_LEN: -1
      LABELS_NUM: 1000
      TEMP_NAME: logit_scale_img_cls
    LOSSES:
      NAMES: ['LabelSmoothingCrossEntropy', 'Accuracy']
      LABELSMOOTHING: 0.1
      REDUCTION: 'mean'
    INFERENCE:
      NAME: 'ImageNetEvaler'
      ID_KEY: 'image_id'
      VALUE: 'cls_logits'
      VAL_ANNFILE: 'open_source_dataset/imagenet/meta/val.txt'
      TEST_ANNFILE: ''
      GENERATION_MODE: False



ENGINE:
  NAME: 'UnifiedTrainer'
 
MODEL:
  META_ARCHITECTURE: 'MultiTaskTransformerEncoder'
  ENCODER: 'UnifiedBertEncoder'

  SHARE_LAYERNORM: True
  BERT:
    NORMALIZE_DECISION: "BERTPre" 
    DROP_PATH_PROB: 0.0
    DROP_PATH_PROB_FIXED: True


  MODEL_EMA: False
  MODEL_EMA_DECAY: 0.9999

  MAEParamsInit: True
  POSEMBEDFIX: True


  IMG_INPUT_SIZE: 224
  PATCH_SIZE: 16
  
  POSEMBED_SCALE: !!python/object/apply:eval ["160/224"]
  CHECKPOINT_FILETER: False 
  OLD_CHECKPONT: True 

  LAYER_SCALE: True 
  LAYER_SCALE_INIT: 1e-3

    # prompt
  PROMPT: True
  PROMPT_PARAM: ["s_token_bias", "norm", "prompt_embed", "deep_prompt_embedding", "fc_prompt", "similarity_weight", "ln_post"] # ["s_token_bias", "LayerNorm", "prompt_embed", "prompt_fc", "similarity_weight"]
  FC_PROMPT: True
  FC_PROMPT_OUT: 1000

  # #################################### prompt embedding ####################################
  PROMPT_EMBED: #### activated only when the
    NAME: 'PrefixPromptEmbedding'
    ACTIVATION: 'none'
    ELU_ALPHA: 0.5
    USE_NORM: False
    DROPOUT: 0.0
    WITH_POS: False
    INPUT_PROMPT: False 
    TARGET_PROMPT: False
    DEEP_PROMPT: True 
    TARGET_DEEP_PROMPT: True 
    SHARE_DEEP_PROMPT: False  
    PROMPT_LENGTH: 10
    TARGET_PROMPT_LENGTH: 1
    INPUT_DEEP_PROMPT_LENGTH: 10
    TARGET_DEEP_PROMPT_LENGTH: 10
    LABLE_PROMPT: True
    LABEL_SIZE: 1000

DATALOADER:
  USE_WEIGHTED_SAMPLER: True
  UNIFIED_DATASET: True 
  NUM_WORKERS: 16

  PADDING_TO_MAX: False # True for debugging or token moe with distributed moe 


####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  TORCH_OPTIMIZER: True
  PARAMS_SEPERATE: True
  # PARAMS_GROUP: True
  # EPOCH: 1
  MAX_ITER: 2500
  CHECKPOINT_PERIOD: 50000
  EVAL_PERIOD: 500
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  WEIGHT_DECAY_EMBEDDING: 0.0
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.95]
  EPS: 1e-6
  GRAD_CLIP: 0.1
  GRAD_CLIP_TYPE: 'norm'
  ACCUM_ITER: 0
  AMP_FP16: True
  APEX_FP16: False # dangerous

  WRITE_PERIOD: 50
  MIN_LOSS_SCLE: 2048.0
  # BF16: False # True
  # ZEROSTAGE: 2

  LOSS_SCALE_WINDOW: 200





  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'WarmupCosine'
  WARMUP: 500
  MIN_LR: 0.000001


